# coding: utf-8

"""
    Swagger Functions Store - OpenAPI 3.0

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.function_job import FunctionJob

class TestFunctionJob(unittest.TestCase):
    """FunctionJob unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FunctionJob:
        """Test FunctionJob
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FunctionJob`
        """
        model = FunctionJob()
        if include_optional:
            return FunctionJob(
                id = 56,
                function_id = 56,
                status = 'PENDING',
                inputs = None,
                outputs = None,
                job_info = None,
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return FunctionJob(
                function_id = 56,
        )
        """

    def testFunctionJob(self):
        """Test FunctionJob"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
