# coding: utf-8

"""
    Swagger Functions Store - OpenAPI 3.0

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.function_job_collection import FunctionJobCollection

class TestFunctionJobCollection(unittest.TestCase):
    """FunctionJobCollection unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FunctionJobCollection:
        """Test FunctionJobCollection
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FunctionJobCollection`
        """
        model = FunctionJobCollection()
        if include_optional:
            return FunctionJobCollection(
                id = 56,
                name = '',
                description = '',
                job_ids = [
                    56
                    ],
                status = ''
            )
        else:
            return FunctionJobCollection(
                id = 56,
                name = '',
                description = '',
                job_ids = [
                    56
                    ],
                status = '',
        )
        """

    def testFunctionJobCollection(self):
        """Test FunctionJobCollection"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
