# coding: utf-8

"""
    Swagger Functions Store - OpenAPI 3.0

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.function import Function

class TestFunction(unittest.TestCase):
    """Function unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Function:
        """Test Function
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Function`
        """
        model = Function()
        if include_optional:
            return Function(
                id = 56,
                name = '',
                type = '',
                url = '',
                description = '',
                input_schema = None,
                output_schema = None,
                tags = [
                    ''
                    ]
            )
        else:
            return Function(
                name = '',
                type = '',
                url = '',
                description = '',
        )
        """

    def testFunction(self):
        """Test Function"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
