# coding: utf-8

"""
    Swagger Functions Store - OpenAPI 3.0

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.function_job_collection_api import FunctionJobCollectionApi


class TestFunctionJobCollectionApi(unittest.TestCase):
    """FunctionJobCollectionApi unit test stubs"""

    def setUp(self) -> None:
        self.api = FunctionJobCollectionApi()

    def tearDown(self) -> None:
        pass

    def test_create_function_job_collection(self) -> None:
        """Test case for create_function_job_collection

        Create Function Job Collection
        """
        pass

    def test_get_collection_status(self) -> None:
        """Test case for get_collection_status

        Get Collection Status
        """
        pass

    def test_list_function_job_collections(self) -> None:
        """Test case for list_function_job_collections

        List Function Job Collections
        """
        pass


if __name__ == '__main__':
    unittest.main()
