# coding: utf-8

"""
    Swagger Functions Store - OpenAPI 3.0

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.function_api import FunctionApi


class TestFunctionApi(unittest.TestCase):
    """FunctionApi unit test stubs"""

    def setUp(self) -> None:
        self.api = FunctionApi()

    def tearDown(self) -> None:
        pass

    def test_batch_run_function(self) -> None:
        """Test case for batch_run_function

        Batch Run Function
        """
        pass

    def test_create_function(self) -> None:
        """Test case for create_function

        Create Function
        """
        pass

    def test_delete_all_functions(self) -> None:
        """Test case for delete_all_functions

        Delete All Functions
        """
        pass

    def test_list_functions(self) -> None:
        """Test case for list_functions

        List Functions
        """
        pass

    def test_map_function(self) -> None:
        """Test case for map_function

        Map Function
        """
        pass

    def test_run_function(self) -> None:
        """Test case for run_function

        Run Function
        """
        pass

    def test_search_functions_by_name(self) -> None:
        """Test case for search_functions_by_name

        Search Functions By Name
        """
        pass

    def test_search_functions_by_tags(self) -> None:
        """Test case for search_functions_by_tags

        Search Functions By Tags
        """
        pass

    def test_update_function_config_function_config_post(self) -> None:
        """Test case for update_function_config_function_config_post

        Update Function Config
        """
        pass


if __name__ == '__main__':
    unittest.main()
