# coding: utf-8

"""
    Swagger Functions Store - OpenAPI 3.0

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.function_job_api import FunctionJobApi


class TestFunctionJobApi(unittest.TestCase):
    """FunctionJobApi unit test stubs"""

    def setUp(self) -> None:
        self.api = FunctionJobApi()

    def tearDown(self) -> None:
        pass

    def test_get_function_job(self) -> None:
        """Test case for get_function_job

        Get Function Job
        """
        pass

    def test_get_function_jobs(self) -> None:
        """Test case for get_function_jobs

        Get Function Jobs
        """
        pass

    def test_get_jobs_status(self) -> None:
        """Test case for get_jobs_status

        Get Jobs Status
        """
        pass

    def test_list_function_jobs(self) -> None:
        """Test case for list_function_jobs

        List all function jobs with optional filtering
        """
        pass


if __name__ == '__main__':
    unittest.main()
